services:
  database:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_DATABASE: symfony
    command:
      - '--default-authentication-plugin=caching_sha2_password'
      - '--sql_mode='
      - '--max_allowed_packet=1073741824'
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "root", "-psymfony", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 30
    ports:
      - '3306:3306'

  php_api:
    build:
      target: php_dev
      context: .
    depends_on:
      database:
        condition: service_healthy
    environment:
      XDEBUG_MODE: "off"
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
        client_port=9003
        idekey=PHPSTORM
      PHP_IDE_CONFIG: "serverName=opencal-api"
      TIMEZONE: Europe/Berlin
      PS1: '[opencal-api]::$$(pwd) # '
      FRONTEND_HOST: 'localhost'
      USE_SSL: false
      APP_ENV: dev
    volumes:
      - php_socket:/var/run/php
      - ./:/srv/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx_api:
    build:
      target: nginx_dev
      context: .
    depends_on:
      - php_api
    # Comment out this volume in production
    volumes:
      - php_socket:/var/run/php
      - ./public:/srv/app/public
    ports:
      - '8080:80'

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  radicale:
    image: tomsquest/docker-radicale:latest
    container_name: radicale
    ports:
      - "5232:5232"
    volumes:
      - ./dev/caldav/data:/data
    environment:
      - RADICALE_CONFIG=/data/config
    restart: unless-stopped

volumes:
  php_socket:
  database:
    driver: local
